# Generated by Django 3.1.5 on 2021-01-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanarCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_id', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type_line', models.CharField(max_length=100)),
                ('oracle_text', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
